import{i as l,S as g,a as y}from"./assets/vendor-951421c8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const L="https://pixabay.com/api/",b="42149629-e1e8d2a9238f015bc3d9ce966",o={form:document.getElementById("form"),resultContainer:document.getElementById("result-container"),loadingIndicator:document.querySelector(".loader"),loadMoreButton:document.querySelector(".load-more-button")},d=15;let m=1,c="";o.form.addEventListener("submit",v);o.loadMoreButton.addEventListener("click",p);function w(){o.resultContainer.innerHTML=""}function M(){o.loadingIndicator.style.display="block"}function u(){o.loadingIndicator.style.display="none"}async function v(a){a.preventDefault();const t=a.currentTarget;if(c=t.elements.search.value.trim(),w(),M(),c.length===0){l.show({message:"Please, try again!",color:"red"}),u(),o.loadMoreButton.classList.add("is-hidden");return}try{const n=(await h(c)).hits;if(n.length===0)l.show({message:"Sorry, there are no images matching your search query. Please try again!"});else{let e="";for(const s of n)e+=f(s);o.resultContainer.innerHTML=e;const r=new g(".image-container a",{captionsData:"alt",captionDelay:250})}n.length>0?(o.loadMoreButton.classList.remove("is-hidden"),o.loadMoreButton.addEventListener("click",p)):o.loadMoreButton.classList.add("is-hidden")}catch{l.show({message:"Sorry, there are no images matching your search query. Please try again!"})}finally{u(),t.reset()}}async function h(a){try{return(await y.get(L,{params:{key:b,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:d,page:m}})).data}catch(t){throw new Error(`Error fetching images: ${t.message}`)}}function f({likes:a,views:t,comments:i,downloads:n,tags:e,webformatURL:r,largeImageURL:s}){return`<li class="image-container">
      <a class="gallery-link" href="${s}">
       <img
         class="gallery-image"
         src="${r}"
         alt="${e}"
       />
      </a>
      <div class="overlay">
      <p>likes<br>${a}</p>
      <p>views<br>${t}</p>
      <p>comments<br>${i}</p>
      <p>downloads<br>${n}</p></div>
  </li>`}async function p(){m+=1;try{const i=(await h(c)).hits;if(i.length>0){let n=" ";for(const r of i)n+=f(r);o.resultContainer.innerHTML+=n;const e=new g(".image-container a",{captionsData:"alt",captionDelay:250});i.length>=d?o.loadMoreButton.classList.remove("is-hidden"):o.loadMoreButton.classList.add("is-hidden")}}catch(t){console.error("Error loading more pictures:",t)}const a=o.resultContainer.lastElementChild;if(a){const t=a.getBoundingClientRect().height;window.scrollBy({top:t*d,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
